// .env <-> SSM parameter mapping.
// File convention:
//   TEST=23            # default: String
//
//   # string
//   A=42
//   B=24
//
//   # secret           # -> SecureString
//   C=23
//   D=32
//
//   # list             # -> StringList
//   E=1,2,3
//   F=4,5,6

export type ParamType = "String" | "SecureString" | "StringList";

export interface FileParam {
  key: string;
  value: string;
  type: ParamType;
}

export const ENV_FORMAT_HELP = `Env file format:
  KEY=value              default type is String
  # string               following keys are String
  # secret               following keys are SecureString
  # list                 following keys are StringList

Example:
  TEST=23
  # string
  A=42
  # secret
  B=32
  # list
  C=1,2,3

Rules:
  - single/double quotes around values are stripped
  - blank lines and unknown "# comments" are ignored
  - duplicate keys: last wins
  - keys may contain [a-zA-Z0-9_. -], no slashes
  - list values split on "," and are trimmed`;

const KEY_RE = /^[a-zA-Z0-9_.-]+$/;

function sectionOfMarker(line: string): ParamType | null {
  // Accepts "# string", "#string", "# secret", "#securestring", "# list".
  const m = line.match(/^\s*#\s*([a-z]+)\s*$/i);
  if (!m) return null;
  const word = m[1].toLowerCase();
  if (word === "string") return "String";
  if (word === "secret" || word === "securestring") return "SecureString";
  if (word === "list" || word === "stringlist") return "StringList";
  return null;
}

function stripQuotes(value: string): string {
  if (value.length >= 2) {
    const first = value[0];
    const last = value[value.length - 1];
    if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
      return value.slice(1, -1);
    }
  }
  return value;
}

export function parseEnvFile(content: string): {
  params: FileParam[];
  warnings: string[];
} {
  const warnings: string[] = [];
  const byKey = new Map<string, FileParam>();
  const order: string[] = [];
  let current: ParamType = "String";

  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const trimmed = raw.trim();
    if (trimmed === "") continue;

    const section = sectionOfMarker(trimmed);
    if (section) {
      current = section;
      continue;
    }
    if (trimmed.startsWith("#")) continue; // unknown comment, ignore

    let line = trimmed;
    if (/^export\s+/i.test(line)) line = line.replace(/^export\s+/i, "").trim();

    const eq = line.indexOf("=");
    if (eq <= 0) {
      throw new Error(`Line ${i + 1}: expected KEY=value, got: ${raw}`);
    }
    const key = line.slice(0, eq).trim();
    const rawValue = line.slice(eq + 1).trim();
    if (!key || !KEY_RE.test(key)) {
      throw new Error(
        `Line ${i + 1}: invalid key "${key}" (allowed: [a-zA-Z0-9_. -]).`,
      );
    }
    const value = stripQuotes(rawValue);

    if (current === "StringList") {
      const items = value.split(",").map((s) => s.trim());
      if (items.some((s) => s === "")) {
        throw new Error(`Line ${i + 1}: list "${key}" contains an empty item.`);
      }
    }

    if (byKey.has(key))
      warnings.push(`Duplicate key "${key}" on line ${i + 1}: last wins.`);
    else order.push(key);
    byKey.set(key, { key, value, type: current });
  }

  return { params: order.map((k) => byKey.get(k)!), warnings };
}

export function emitEnvFile(params: FileParam[]): string {
  const groups: Array<{ type: ParamType; marker: string }> = [
    { type: "String", marker: "# string" },
    { type: "SecureString", marker: "# secret" },
    { type: "StringList", marker: "# list" },
  ];
  const lines: string[] = [
    "# Generated by asdi param pull. See: asdi param --help",
  ];
  for (const g of groups) {
    const items = params
      .filter((p) => p.type === g.type)
      .sort((a, b) => a.key.localeCompare(b.key));
    if (items.length === 0) continue;
    lines.push("", g.marker);
    for (const p of items) lines.push(`${p.key}=${p.value}`);
  }
  lines.push("");
  return lines.join("\n");
}
